pr:
- none

trigger: 
  branches:
    include:
    - feature/*
    
parameters:
  - name: ServiceConnection
    displayName: Service Connection
    type: string
    default: serviceconnection-peerinsights
        
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Setup_Dev_Env
    displayName: 'Setup Development Environment'
    jobs:
    - job: 'SetupDev'
      displayName: 'Setup Development Environment'
      steps:
      - checkout: self

      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{ parameters.ServiceConnection }}
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |        
            fabric_token=$(az account get-access-token --resource https://api.fabric.microsoft.com --query accessToken -o tsv)
            echo "##vso[task.setvariable variable=fabric_token]$fabric_token"
        displayName: 'Get MS Entra ID token for required resources'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.12'
        displayName: 'Use Python 3.12'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install Python requirements'
        workingDirectory: '$(Build.SourcesDirectory)/automation/prerequisites'

      - task: PythonScript@0
        inputs:
          scriptSource: 'filePath'
          scriptPath: '$(Build.SourcesDirectory)/automation/cicd/scripts/feature_setup.py'
          arguments: '--fabric_token $(fabric_token) --action create'
        displayName: 'Setup Feature Workspaces'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)